# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 长安曹公子的博客
subtitle: 生活不仅有coding，还有文字和音乐
prefix_description: 爱coding，爱前端，爱文字，爱音乐的半文艺前端程序员
description: 谜一样的浮世，每一步都未知
keyword: 长安曹公子的博客,长安曹公子,博客,前端技术,web开发,HTML,Javascript,CSS,Vue.js,React.js,Node.js,文字,生活,摄影,音乐
author: 长安曹公子
language: zh-CN
email: changAncgz@163.com #联系邮箱
timezone:
avatar:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://webCaolixin.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  # ###ADD### prettify代码高亮插件
  ## 告诉hexo对plugins目录下的所有文件跳过解析渲染，因为测试时发现如果不配置，加载prettify的相关js会报脚本错误，猜测hexo渲染造成的编码问题
  - "theme/matery/source/libs/prettify/**"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

# ###ADD### hexo-theme-matery主题中使用hexo-prism-plugin的 Hexo 插件来做代码高亮
# prism_plugin:
## enable: true
## mode: 'preprocess'    # realtime/preprocess
## theme: 'tomorrow'
## line_number: false    # default false
## custom_css:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HHbushu:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
## theme: next
## theme: landscape
theme: matery

# Social links
social:
  GitHub: https://github.com/webCaolixin || github
  Weibo: https://www.weibo.com/u/5153743489 || weibo

feed:
type: atom
path: atom.xml
limit: 20
hub:

# Creative Commons 4.0 International License.(一种许可协议)
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 百度主动推送,与自动推送相配合以让百度更快收录文章  
baidu_url_submit:
  count: 2 ## 提交最新的一个链接
  host: https://webcaolixin.github.io ## 在百度站长平台中注册的域名
  token: nefMs8KoHUDC4aJN ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Specify the date when the site was setup
since: 2018

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Stylus
stylus:
  compress: false

# minifier html,css,js,image
html_minifier:
  enable: true
  exclude: 
css_minifier:
  enable: true
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: https://github.com/webCaolixin/webCaolixin.github.io
  branch: master
- type: baidu_url_submitter ## 这是新加的

leancloud_counter_security:
  enable_sync: true
  app_id: 8QCStxYhzTmcfzSimF0rbgWW-gzGzoHsz
  app_key: cRiWQY0NyClTBqBiF0HrCFgw
  username:  MagicEyes # Will be asked while deploying if is left blank
  password:  Clx0298588123 # Recommmended to be left blank. Will be asked while deploying if is left blank